### PR TITLE
Integrated Qdrant FastEmbed to Phidata embedder options

### PR DESCRIPTION
**Pull request by sashank5644**
# Integrated Qdrant FastEmbed embedding option for advantageous embeddings.

**Overview**

Qdrant FastEmbed is a lightweight, efficient embedding library optimized for fast inference and limited dependencies. Some if its advantages include:

1. High-Speed Embedding Generation: (50% faster) than traditional PyTorch-based transformers, making it ideal for real-time applications.
2. Resource Efficiency: With model quantization and ONNX Runtime integration, FastEmbed minimizes memory and CPU use.
3. Enhanced Retrieval with Prefix-Based Embeddings: FastEmbed supports specialized input prefixes like "query" and "Passage" which allows model to generate differentiated embeddings for queries and documents, optimizing retrieval accuracy and semantic search.

### CODE REVIEW

**Comment by manthanguptaa** [comment]
@sashank5644 this is a really great PR! Can you also add an example of using this embedder? Make a folder under the cookbook folder with the name embedder and then add an example for the same.

**Comment by sashank5644** [comment]
@manthanguptaa for the example text to embed, is there any specific "testing text" phidata uses, or should I just run a simple example text maybe for a recipe, and then embed that using the FastEmbed.

**Comment by manthanguptaa** [comment]
@sashank5644 we don't have a particular example text but would prefer having a generic text. Recipe sounds good to me.

**Comment by sashank5644** [comment]
@manthanguptaa Sorry I accidentally deleted the head repo, is it possible to reopen this PR.

**Pull request closed without merging**
