### PR TITLE
 add-azure-openai-embedder

### PR DESCRIPTION
**Pull request by luckzack**
1. embedder: support azure openai deployment
2. tests: add test_azure_openai_embedder

### CODE REVIEW

**Comment by luckzack** [comment]
@ysolanky 
PTAL😀

**Comment by jacobweiss2305** [comment]
Thanks @luckzack gonna test this out today!

**Review by jacobweiss2305 — APPROVED** [review]
LGTM

**Comment by ysolanky** [comment]
Hey @luckzack made some small changes on top of your commits here: https://github.com/phidatahq/phidata/pull/1007

**Pull request merged**
