### PR TITLE
Add Cookbooks for Integrating Phidata with Portkey

### PR DESCRIPTION
**Pull request by siddharthsambharia-portkey**
This PR adds two new cookbooks to the Phidata repository, demonstrating how to integrate Phidata with Portkey.

1. Phidata_with_portkey: This cookbook provides step-by-step instructions on integrating Phidata with Portkey, highlighting use cases of Portkey with Phidata.

2. Phidata_with_Perplexity: This cookbook offers a guide on integrating Phidata with Perplexity using Portkey, showcasing its capabilities and practical applications.

### CODE REVIEW

**Review by ashpreetbedi — APPROVED** [review]

**Comment by ashpreetbedi** [comment]
@siddharthsambharia-portkey this is amazing! love portkey and excited to build more with you

**Comment by siddharthsambharia-portkey** [comment]
Great job with Phidata! Definitely excited to build together @ashpreetbedi

**Comment by bitsnaps** [comment]
Now, it is broken, I'll let you know when it's fixed.

**Comment by bitsnaps** [comment]
> @bitsnaps just checking, did you get any chance to fix it?

I'm not sure! nothing from what I've already tried, I'd rather go for [LangSmith](https://www.langchain.com/langsmith), it worked well with Flowise for me, but there is no [support](https://github.com/search?q=org%3Aphidatahq%20langsmith&type=code) AFAIK yet.

**Comment by siddharthsambharia-portkey** [comment]
> @bitsnaps just checking, did you get any chance to fix it?
> 
> @ashpreetbedi what's the best observability tool that goes well with phidata. For building production grade apps, it'd be great if you could suggest one. Right now, its bit hard to get a sense of cost involved, behind each requests.

hey @Joyfred, just found out that this is broken. Here is a guide on Portkey's docs on how to use it with Phidata. Let me know if this helps- https://portkey.ai/docs/integrations/agents/phidata#phidata

I will raise a new PR on Portkey integration with Phidata @ashpreetbedi. Thanks!

**Comment by siddharthsambharia-portkey** [comment]
let me check this myself and get back to you. are using Portkey's hosted version or opensource gateway?

**Comment by siddharthsambharia-portkey** [comment]
hey @Joyfred just tried it out. seems to be working fine with me. 
here's the link to the notebook [Phidata x Portkey Colab Notebook](https://colab.research.google.com/drive/1KDR0x03Ho3Vl3QthC3o1ozCpkuhYjv7p?usp=sharing)

if you have already tried this, can you share your code on [Portkey's discord](https://discord.gg/QYerkNGYHC)? I can help you debug it

**Pull request merged**
