### PR TITLE
fix batch scripts

### PR DESCRIPTION
**Pull request by hansipie**
->'print_heading' was not found + erratic behaviour
+ replace 'echo' by 'print_heading' in 'create_venv.bat'
+ fix doc:  'create_venv_win.bat' to 'create_venv.bat'

### CODE REVIEW

**Comment by jacobweiss2305** [comment]
@ashpreetbedi LGTM. Tested and it works.

**Review by jacobweiss2305 — APPROVED** [review]
LGTM

**Comment by hansipie** [comment]
hello .... merging is blocked .... is there someting i have to do ?

**Comment by jacobweiss2305** [comment]
@ashpreetbedi will finish review and merge

**Pull request closed without merging**
