### PR TITLE
Weaviate Vectordb implementation

### PR DESCRIPTION
**Pull request by rohinish404**
Issue #1324

### CODE REVIEW

**Comment by rohinish404** [comment]
@manthanguptaa I have few doubts - 
- My current implementation is a bit wrong for client connection. Connect to custom is not something where  i can connect to cloud weaviate instances. so for providing both the options to connect locally as well as cloud instance how would i go about it? Should i pass an arguement using which the user can pass what type of client connection they want to instantiate?
- And for the insert function should i follow the batch import like below?
```
import weaviate
from weaviate.classes.init import Auth
import requests, json, os

# Best practice: store your credentials in environment variables
wcd_url = os.environ["WCD_URL"]
wcd_api_key = os.environ["WCD_API_KEY"]
openai_api_key = os.environ["OPENAI_APIKEY"]

client = weaviate.connect_to_weaviate_cloud(
    cluster_url=wcd_url,                                    # Replace with your Weaviate Cloud URL
    auth_credentials=Auth.api_key(wcd_api_key),             # Replace with your Weaviate Cloud key
    headers={"X-OpenAI-Api-Key": openai_api_key},           # Replace with your OpenAI API key
)

resp = requests.get(
    "https://raw.githubusercontent.com/weaviate-tutorials/quickstart/main/data/jeopardy_tiny.json"
)
data = json.loads(resp.text)

questions = client.collections.get("Question")

with questions.batch.dynamic() as batch:
    for d in data:
        batch.add_object({
            "answer": d["Answer"],
            "question": d["Question"],
            "category": d["Category"],
        })

client.close()  # Free up resources

```

**Comment by manthanguptaa** [comment]
Hey @rohinish404, can you add a cookbook for this example? It will help me test it and also help you with your doubts.

**Comment by manthanguptaa** [comment]
@rohinish404 just looked at connections for weaviate. Support cloud and local for now. Let's hold off on the custom connection. Take the URL, API key, host, port, and grpc_port in the class. Check what params are provided and connect accordingly. Throw error accordingly as well

**Comment by manthanguptaa** [comment]
And as for insertion. Give option to allow user to have batch inserts as well as single inserts

**Pull request closed without merging**
