### PR TITLE
Changed csv.py, docx.py and text.py files.

### PR DESCRIPTION
**Pull request by Tlionn**
Changed csv.py, docx.py and text.py files. They can now handle uploaded files and paths. Earlier code handled only PDF uploads. Now text, CSV, docx and PDF files can be uploaded.

### CODE REVIEW

**Comment by jacobweiss2305** [comment]
@Tlionn do you mind adding cookbook example that I can test?

**Comment by Tlionn** [comment]
Hey Jacob
Sure, I will do this in a few hours.
Thanks!

**Comment by Tlionn** [comment]
@jacobweiss2305 I have added a cookbook example, please check and let me know if I have to do anything else. Thanks!

**Comment by jacobweiss2305** [comment]
https://github.com/phidatahq/phidata/pull/1168

**Pull request closed without merging**
