### PR TITLE
chromadb implementation w.i.p

### PR DESCRIPTION
**Pull request by hoxsec**
new file:   phi/vectordb/chromadb/chromadb.py

### CODE REVIEW

**Comment by hoxsec** [comment]
> can we collaborate on this? @hoxsec 
> 

Ofcourse, go ahead.

**Comment by Hk669** [comment]
can you share me information on what you are working on actually?

**Comment by Hk669** [comment]
that's because you are returning the `chromadb.Client()` , instead create a new type for the `chromadb.Client()`.

`chromaClient = Type[chromaeb.Client()]`

this should work. @hoxsec

**Comment by ashpreetbedi** [comment]
Thanks for this @Hk669 and @hoxsec, happy to review when ready :)

**Pull request closed without merging**
