### PR TITLE
add support for couchbase #1375

### PR DESCRIPTION
**Pull request by Himasnhu-AT**
This pull request introduces a new Couchbase integration for the project, including implementing a Couchbase-based vector database, a Couchbase assistant, and corresponding tests. The most important changes include the addition of the `CouchbaseVectorDb` class, the `couchbase_assistant` script, and the necessary dependencies and documentation updates.

### Couchbase Integration:

* [`phi/vectordb/couchbase/couchbase.py`](diffhunk://#diff-d8494317ab9c927578c3c9c10b54984f4bd3b41db32179336b577a6f19781467R1-R130): Implemented `CouchbaseVectorDb` class to handle interactions with Couchbase, including methods for creating collections, checking document existence, inserting documents, and searching documents.
* [`cookbook/assistants/integrations/couchbase/assistant.py`](diffhunk://#diff-dba280a712ff1a4a10e94d2a1c779cc0ed4cb4b4cd6bd7a5dc26f7bfd820ff5fR1-R61): Added `couchbase_assistant` script to run a Couchbase-based assistant, utilizing the `CouchbaseVectorDb` and `PDFUrlKnowledgeBase`.

### Documentation and Dependencies:

* [`cookbook/assistants/integrations/couchbase/README.md`](diffhunk://#diff-e2263d8858ef1824546396a55faf5e1eab530a19678e431ab6148720fa76eddbR1-R22): Updated README with instructions on setting up and running the Couchbase assistant.
* [`pyproject.toml`](diffhunk://#diff-50c86b7ed8ac2cf95bd48334961bf0530cdc77b5a56f852c5c61b89d735fd711R105): Added `couchbase` package dependency.

### Testing:

* [`tests/test_couchbase_integration.py`](diffhunk://#diff-24853ec3327a3610d212e03053dec50130f6223c90af71c2f026003291a9815bR1-R112): Added unit tests for `CouchbaseVectorDb` to ensure proper functionality of collection creation, document existence checks, document insertion, and searches.

### CODE REVIEW

**Comment by Himasnhu-AT** [comment]
PS: more familiar with pytest, so used `unittest` for testing. can migrate it to pytest if required

**Review by shivay-couchbase — CHANGES_REQUESTED** [review]
Not sure if you used some sort of an AI tool to generate this code so quickly, but be advised that Couchbase uses a vector search index, as it is not only a vector database. So whenever you store a vector, first you have to define a vector search index. I will recommend having a look at the implementation of Langchain Couchbase Vector Store: https://github.com/langchain-ai/langchain/blob/master/libs/partners/couchbase/langchain_couchbase/vectorstores.py

**Comment by Himasnhu-AT** [comment]
Thanks for the ref. Would take a look at it. Wasn't able to go through the docs much.

**Comment by Himasnhu-AT** [comment]
Quick question, they set default batch size as 100. Is their any good number according to you?

**Comment by shivay-couchbase** [comment]
I am not aware of the value, but perhaps try with 500 / 1000 - it should work

**Pull request closed without merging**
