### PR TITLE
Fix Ollama `Structured Output` infinite loop

### PR DESCRIPTION
**Pull request by CorrM**
- Fix Ollama `Structured Output` infinite loop
- Added two tests file for ollama

### CODE REVIEW

**Comment by ashpreetbedi** [comment]
@CorrM looking

**Comment by ashpreetbedi** [comment]
testing today locally

**Comment by jacobweiss2305** [comment]
This is a good PR thanks @CorrM

**Review by jacobweiss2305 — APPROVED** [review]
Tested and approved

**Review by ashpreetbedi — APPROVED** [review]

**Pull request merged**
