### PR TITLE
Added "vector" datatype for singlestore vectordb.

### PR DESCRIPTION
**Pull request by vishwajeetdabholkar**
Added support for "vector" datatype for singlestore vectordb. Modified create, insert, upsert and search functions accordingly.

### CODE REVIEW

**Comment by vishwajeetdabholkar** [comment]
@ashpreetbedi  @ysolanky guys could you please review this or add it manually? Many people are trying out SingleStore as a vector store with phidata and want to use vector datatype.

**Comment by ysolanky** [comment]
Testing it out today @vishwajeetdabholkar

**Comment by vishwajeetdabholkar** [comment]
@ysolanky  @ashpreetbedi  Made the changes and added an example for SQL ASSISTANT  for singlestore
could you please confirm these changes ?

**Comment by vishwajeetdabholkar** [comment]
Hey @ashpreetbedi  I fixed the error we were getting for upserting LLM replies 
the error was : `UnicodeDecodeError: 'utf-8' codec can't decode byte 0xed in position 86: invalid continuation byte`

Please add these changes to singlestore class, we really need it.

**Pull request closed without merging**
